apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::049167128364:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1TPVL1NWPE2EG
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::049167128364:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-06-11T07:17:20Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1463"
  uid: 13ae887d-d7ed-42c4-863e-8befc7f04a9f
